export const dummy = [
  {
    unit_reported: "PRO13",
    enemy_unit: "NEMRC",
    date_of_activity: "Oct 24, 2023",
    activity: "",
    location: "Brgy Santol, Mangga, Davao City",
    bdp_status: "NON-BDP",
    rpsb_deployment_status: "With Deployment",
  },
  {
    unit_reported: "PRO13",
    enemy_unit: "NEMRC",
    date_of_activity: "Oct 24, 2023",
    activity: "",
    location: "Brgy Santol, Mangga, Davao City",
    bdp_status: "NON-BDP",
    rpsb_deployment_status: "With Deployment",
  },
  {
    unit_reported: "PRO13",
    enemy_unit: "NEMRC",
    date_of_activity: "Oct 24, 2023",
    activity: "",
    location: "Brgy Santol, Mangga, Davao City",
    bdp_status: "NON-BDP",
    rpsb_deployment_status: "With Deployment",
  },
  {
    unit_reported: "PRO13",
    enemy_unit: "NEMRC",
    date_of_activity: "Oct 24, 2023",
    activity: "",
    location: "Brgy Santol, Mangga, Davao City",
    bdp_status: "NON-BDP",
    rpsb_deployment_status: "With Deployment",
  },
  {
    unit_reported: "PRO13",
    enemy_unit: "NEMRC",
    date_of_activity: "Oct 24, 2023",
    activity: "",
    location: "Brgy Santol, Mangga, Davao City",
    bdp_status: "NON-BDP",
    rpsb_deployment_status: "With Deployment",
  },
  {
    unit_reported: "PRO13",
    enemy_unit: "NEMRC",
    date_of_activity: "Oct 24, 2023",
    activity: "",
    location: "Brgy Santol, Mangga, Davao City",
    bdp_status: "NON-BDP",
    rpsb_deployment_status: "With Deployment",
  },
  {
    unit_reported: "PRO13",
    enemy_unit: "NCMRC",
    date_of_activity: "Oct 24, 2023",
    activity: "",
    location: "Brgy Santol, Mangga, Davao City",
    bdp_status: "NON-BDP",
    rpsb_deployment_status: "With Deployment",
  },
  {
    unit_reported: "PRO13",
    enemy_unit: "NCMRC",
    date_of_activity: "Oct 24, 2023",
    activity: "",
    location: "Brgy Santol, Mangga, Davao City",
    bdp_status: "NON-BDP",
    rpsb_deployment_status: "With Deployment",
  },
  {
    unit_reported: "PRO13",
    enemy_unit: "SMRC",
    date_of_activity: "Oct 24, 2023",
    activity: "",
    location: "Brgy Santol, Mangga, Davao City",
    bdp_status: "NON-BDP",
    rpsb_deployment_status: "With Deployment",
  },
  {
    unit_reported: "PRO13",
    enemy_unit: "SMRC",
    date_of_activity: "Oct 27, 2023",
    activity: "",
    location: "Brgy Santol, Mangga, Davao City",
    bdp_status: "NON-BDP",
    rpsb_deployment_status: "With Deployment",
  },
  {
    unit_reported: "PRO13",
    enemy_unit: "WMRC",
    date_of_activity: "Oct 25, 2023",
    activity: "",
    location: "Brgy Santol, Mangga, Davao City",
    bdp_status: "NON-BDP",
    rpsb_deployment_status: "With Deployment",
  },
  {
    unit_reported: "PRO13",
    enemy_unit: "NEMRC",
    date_of_activity: "Oct 24, 2023",
    activity: "",
    location: "Brgy Santol, Mangga, Davao City",
    bdp_status: "NON-BDP",
    rpsb_deployment_status: "With Deployment",
  },
];
